
spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "v1.1"

cards:
  message: "thank you for contacting cards microservices production team"
  contactDetails:
    developer: "abhinit sharma - product engineer"
    email: "abhinitsharma@gmail.com"
  onCallSupport:
    - 9543211234
    - 9123456789