
spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "v3.1"

loans:
  message: "thank you for contacting loans microservices production team"
  contactDetails:
    developer: "jatin sapra - product engineer"
    email: "jatinsapra@gmail.com"
  onCallSupport:
    - 9543211234
    - 9123456789